"""add biographic information

Revision ID: a4d8296246f3
Revises: e2dd09503c07
Create Date: 2020-03-05 21:40:53.640412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d8296246f3'
down_revision = 'e2dd09503c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address1', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('address2', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'state')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address2')
    op.drop_column('user', 'address1')
    # ### end Alembic commands ###
