"""customer and employee tables

Revision ID: e2dd09503c07
Revises: 9c5bbe3d31f3
Create Date: 2020-03-05 21:20:08.752733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2dd09503c07'
down_revision = '9c5bbe3d31f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loyalty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('employee',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loyalty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('customer')
    # ### end Alembic commands ###
