CREATE TABLE IF NOT EXISTS Customer (
	loyaltyID INT NOT NULL PRIMARY KEY,
	firstName VARCHAR(45) NOT NULL,
	lastName VARCHAR(45) NOT NULL,
	address1 VARCHAR(45) NOT NULL,
	address2 VARCHAR(45) NULL,
	city VARCHAR(45) NOT NULL,
	state VARCHAR(45) NOT NULL,
	zip VARCHAR(45) NOT NULL,
	email VARCHAR(45) NULL,
	phone VARCHAR(45) NULL);

CREATE TABLE IF NOT EXISTS Employee (
	employeeID INT NOT NULL PRIMARY KEY,
	firstName VARCHAR(45) NOT NULL,
	lastName VARCHAR(45) NOT NULL,
	address1 VARCHAR(45) NOT NULL,
	address2 VARCHAR(45) NULL,
	city VARCHAR(45) NOT NULL,
	state VARCHAR(45) NOT NULL,
	zip VARCHAR(45) NOT NULL,
	email VARCHAR(45) NULL,
	phone VARCHAR(45) NULL);

CREATE TABLE IF NOT EXISTS Store (
	storeID INT NOT NULL PRIMARY KEY);

CREATE TABLE IF NOT EXISTS Transaction (
	transactionID SERIAL NOT NULL PRIMARY KEY,
	itemType VARCHAR(45) NOT NULL,
	unit VARCHAR(45) NOT NULL,
	quantity INT NOT NULL,
	date TIMESTAMP NOT NULL,
	description VARCHAR(200) NULL,
	taxYear INT NOT NULL,
	loyaltyID INT NOT NULL REFERENCES Customer(loyaltyID),
	storeID INT NOT NULL REFERENCES Store(storeID)
);
